name: Test workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Yamllint'
      uses: karancode/yamllint-github-action@master
      with:
        yamllint_config_filepath: .yamllint
        yamllint_comment: true
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker build
      run: docker build -t echer:${{ github.sha }} .
