name: Test workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Yamllint'
      uses: karancode/yamllint-github-action@master
      with:
        yamllint_config_filepath: .yamllint
        yamllint_comment: true
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: evgkrsk/etcher
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}.{{patch}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
    -
      name: Build docker image
      id: build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    -
      name: Run Trivy vulnerability scanner (CRIT only)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/evgkrsk/etcher@${{ steps.build.outputs.digest }}'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL'
    -
      name: Run Trivy vulnerability scanner (full list)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/evgkrsk/etcher@${{ steps.build.outputs.digest }}'
