name: Test workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Yamllint'
      uses: karancode/yamllint-github-action@master
      with:
        yamllint_config_filepath: .yamllint
        yamllint_comment: true
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker build
      run: docker build -t evgkrsk/etcher:${{ github.sha }} .
    -
      name: Run Trivy vulnerability scanner (CRIT only)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'evgkrsk/etcher:${{ github.sha }}'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL'
    -
      name: Run Trivy vulnerability scanner (full list)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'evgkrsk/etcher:${{ github.sha }}'
